
const CSV={article:'https://docs.google.com/spreadsheets/d/e/2PACX-1vRtFcnN6Sx_TfSZUOd-z4pJAsdUH9Iwif5O0g511UlRdSj-k3pVMoQJHtYLQhcxOJkpS-BZu0PrI755/pub?output=csv',file:'https://docs.google.com/spreadsheets/d/e/2PACX-1vTRLAWjFV-pv0-Ek3rsR6ITrYwLERjn6gDJES1VfevOZijiFkK4QOIw23gpm4gbJgLm1a6jfxpVFw2L/pub?gid=0&single=true&output=csv',daily:'https://docs.google.com/spreadsheets/d/e/2PACX-1vQ5FAscCEiiTPtwoRATyaWkoibduHw-R46MQAemT32oYDB2tp9zzHh3-uErkSt62dqEEwYcFooC3oyg/pub?gid=0&single=true&output=csv'};
let cache={article:[],file:[],daily:[]},active='article',pageSize=100,shownCount=0,currentFiltered=[],selectedWorks=new Set();
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
$('#tabArticle').onclick=async()=>{setTab('article');await loadList('article')};
$('#tabFile').onclick=async()=>{setTab('file');await loadList('file')};
$('#tabDaily').onclick=async()=>{setTab('daily');await loadList('daily')};
$('#refresh').onclick=async()=>{await loadList(active,true)};
$('#backBottom').onclick=()=>{showList()};
const BM_KEY='reader_bookmark_map';
const getBMMap=()=>{try{return JSON.parse(localStorage.getItem(BM_KEY)||'{}')}catch(e){return {}}};
const saveBM=(k,y)=>{const m=getBMMap(); m[k]=y; localStorage.setItem(BM_KEY,JSON.stringify(m))};
const readBM=(k)=>getBMMap()[k];
$('#bookmark').onclick=()=>{saveBM($('#rTitle').textContent, window.scrollY||0); toast('已加書籤'); $('#bmFloat').classList.remove('hidden')};
$('#bmFloat').onclick=()=>{const y=readBM($('#rTitle').textContent); if(y!=null) window.scrollTo(0,y)};
const FONT_KEY='reader_font_size', FONT_MAP={s:'16px',m:'20px',l:'24px'};
function applyFont(code){document.documentElement.style.setProperty('--fz',FONT_MAP[code]||FONT_MAP.m); for(const b of $$('.segBtn')) b.setAttribute('aria-pressed','false'); const btn=document.querySelector('.segBtn[data-size="'+code+'"]'); if(btn) btn.setAttribute('aria-pressed','true'); localStorage.setItem(FONT_KEY,code)}
for(const b of $$('.segBtn')) b.addEventListener('click',()=>applyFont(b.dataset.size)); applyFont(localStorage.getItem(FONT_KEY)||'m');
function setTab(kind){active=kind; for(const b of $$('nav button')) b.setAttribute('aria-pressed','false'); (kind==='article'?$('#tabArticle'):kind==='file'?$('#tabFile'):$('#tabDaily')).setAttribute('aria-pressed','true'); showList()}
function showList(){$('#reader').classList.add('hidden'); $('#listPanel').classList.remove('hidden'); $('#toolbar').classList.remove('hidden'); window.scrollTo(0,0)}
function showReader(){$('#reader').classList.remove('hidden'); $('#listPanel').classList.add('hidden'); $('#toolbar').classList.add('hidden'); window.scrollTo(0,0)}
function parseCSV(text){const rows=[]; let cur=[], val='', q=false; for(let i=0;i<text.length;i++){const ch=text[i]; if(ch=='"'){ if(q && text[i+1]=='"'){ val+='"'; i++; } else { q=!q; } } else if(ch==',' && !q){ cur.push(val); val=''; } else if((ch=='\n' || ch=='\r') && !q){ if(val!=='' || cur.length>0){ cur.push(val); rows.push(cur); cur=[]; val=''; } } else { val+=ch; } } if(val!=='' || cur.length>0) cur.push(val); if(cur.length>0) rows.push(cur); return rows; }
async function fetchCSV(url){const r=await fetch(url,{cache:'no-store'}); const text=await r.text(); const rows=parseCSV(text); const body=rows[0] && /日期|date|Date/.test(rows[0][0]) ? rows.slice(1):rows; return body.map(c=>({date:c[0]||'', category:c[1]||'', title:c[2]||'', content:c[3]||''})).filter(x=>(x.title.trim()!=='' || x.content.trim()!==''));}
async function loadList(kind){const url=kind==='article'?CSV.article:kind==='file'?CSV.file:CSV.daily; try{const data=await fetchCSV(url); cache[kind]=data; buildChips(data); renderList(kind,data);}catch(e){console.error(e); renderEmpty('讀取失敗');}}
function buildChips(arr){const wrap=$('#workChips'); const keep=new Set(selectedWorks); const works=Array.from(new Set(arr.map(x=>(x.category||'').trim()).filter(Boolean))).sort(); wrap.innerHTML='<button class="chip active" data-val="">全部</button>'+works.map(w=>'<button class="chip" data-val="'+w+'">'+w+'</button>').join(''); selectedWorks=keep; wrap.querySelectorAll('.chip').forEach(ch=>{ ch.addEventListener('click', ()=>{ const val=ch.getAttribute('data-val'); if(val===''){ selectedWorks.clear(); wrap.querySelectorAll('.chip').forEach(x=>x.classList.remove('active')); ch.classList.add('active'); } else { wrap.querySelector('.chip[data-val=""]').classList.remove('active'); if(selectedWorks.has(val)) selectedWorks.delete(val); else selectedWorks.add(val); ch.classList.toggle('active'); if(selectedWorks.size===0) wrap.querySelector('.chip[data-val=""]').classList.add('active'); } renderList(active, cache[active]); }); const v=ch.getAttribute('data-val'); if(v!=='' && selectedWorks.has(v)) ch.classList.add('active'); }); if(selectedWorks.size===0) wrap.querySelector('.chip[data-val=""]').classList.add('active');}
function renderEmpty(msg){ $('#list').innerHTML = '<li class="meta">'+(msg||'目前沒有內容或搜尋不到。')+'</li>'; $('#loadMoreBox').classList.add('hidden'); }
function renderList(kind,arr){const ul=$('#list'); ul.textContent=''; let data=arr||[]; if(selectedWorks.size>0) data=data.filter(x=>selectedWorks.has((x.category||'').trim())); const q=($('#q').value||'').toLowerCase().trim(); if(!q && data.length>1500) return renderEmpty('資料量較大，請先搜尋（至少輸入 2 個字）'); if(q.length>0){ if(q.length<2) return renderEmpty('請至少輸入 2 個字再搜尋'); data=data.filter(x=>(x.title+x.category+x.content).toLowerCase().includes(q)); } currentFiltered=data; shownCount=0; renderMore(); }
function renderMore(){const ul=$('#list'); const end=Math.min(currentFiltered.length, shownCount+pageSize); if(shownCount===0 && currentFiltered.length===0) return renderEmpty(); const batch=20; let i=shownCount; function pump(){const stop=Math.min(end,i+batch); for(;i<stop;i++){const x=currentFiltered[i]; const li=document.createElement('li'); li.className='card'; const title=x.title&&x.title.trim()!==''?x.title:'(無標題)'; const cat=(x.category||'').trim(); const meta=[x.date, cat?('・'+cat):''].join(''); li.innerHTML='<h3>'+title+'</h3><div class="meta">'+meta+'</div>'; li.onclick=()=>openReader(x); ul.appendChild(li);} if(i<end) requestAnimationFrame(pump); else { shownCount=end; if(shownCount<currentFiltered.length) $('#loadMoreBox').classList.remove('hidden'); else $('#loadMoreBox').classList.add('hidden'); }} pump(); }
function openReader(item){const title=item.title&&item.title.trim()!==''?item.title:'(無標題)'; $('#rTitle').textContent=title; $('#rMeta').textContent=item.date; const el=$('#rContent'); el.textContent=''; progressiveRender(item.content||''); showReader(); const y=readBM(title); $('#bmFloat').classList.toggle('hidden', !(y!=null));}
async function progressiveRender(text){const el=$('#rContent'); const bar=$('#progress'), fill=$('#progress span'); bar.classList.remove('hidden'); const chunk=2000, total=text.length; let shown=0; while(shown<total){ const next=text.slice(shown, shown+chunk); el.append(document.createTextNode(next)); shown+=next.length; fill.style.width=Math.min(100, Math.round((shown/total)*100))+'%'; await new Promise(r=>requestAnimationFrame(r)); } bar.classList.add('hidden'); }
let sx=0, sy=0, tracking=false; const EDGE=90, TH=35, MAXDY=80;
document.addEventListener('touchstart', e=>{ if($('#reader').classList.contains('hidden')) return; if(e.touches.length!==1) return; const t=e.touches[0]; sx=t.clientX; sy=t.clientY; tracking=(sx<=EDGE); }, {passive:true});
document.addEventListener('touchmove',  e=>{ if(!tracking) return; const t=e.touches[0]; const dx=t.clientX-sx; const dy=t.clientY-sy; if(Math.abs(dy)>MAXDY) return; if(dx>TH){ tracking=false; showList(); } }, {passive:true});
document.addEventListener('touchend',   ()=>{ tracking=false }, {passive:true});
let toastTimer=null; function toast(msg){ let t=document.querySelector('#toast'); if(!t){ t=document.createElement('div'); t.id='toast'; Object.assign(t.style,{position:'fixed',bottom:'24px',left:'50%',transform:'translateX(-50%)',background:'rgba(0,0,0,.7)',color:'#fff',padding:'8px 12px',borderRadius:'999px',fontSize:'14px',zIndex:'9999'}); document.body.appendChild(t); } t.textContent=msg; t.style.opacity='1'; clearTimeout(toastTimer); toastTimer=setTimeout(()=>t.style.opacity='0',1200);}
setTab('article'); loadList('article');
